const apiList = [
  {
    name: "getArtList",
    method: "GET",
    desc: "获取市场列表",
    path: "/arts/lists",
    mockPath: "/arts/lists",
    params: {
      page: "",
      per_page: "",
      keyword: "",
    },
    options: {},
  },
  {
    name: "getGroupList",
    method: "GET",
    desc: "获取投票组列表",
    path: "/arts/group",
    mockPath: "/arts/group",
    params: {
      type: "",
      page: "",
      per_page: "",
    },
    options: {},
  },
  {
    name: "getGroupVotedList",
    method: "GET",
    desc: "获取上一期投票组列表",
    path: "/arts/lvr",
    mockPath: "/arts/lvr",
    params: {},
    options: {},
  },
  {
    name: "getGroupVoted",
    method: "GET",
    desc: "获取投票组票数",
    path: "/arts/voted",
    mockPath: "/arts/voted",
    params: {
      sn: "",
    },
    options: {},
  },
  {
    name: "getVoteList",
    method: "GET",
    desc: "获取投票列表",
    path: "/arts/detail",
    mockPath: "/arts/detail",
    params: {
      type: "",
      page: "",
      per_page: "",
    },
    options: {},
  },
  {
    name: "getArtistDetail",
    method: "GET",
    desc: "获取艺术家详情",
    path: "/members/artist",
    mockPath: "/members/artist",
    params: {
      uid: "",
    },
    options: {},
  },
  {
    name: "getArtDetail",
    method: "GET",
    desc: "获取艺术品详情",
    path: "/arts/{:id}",
    mockPath: "/members/artist/{:id}",
    params: {
      uid: "",
    },
    options: {},
  },
  {
    name: "getVotedDetail",
    method: "GET",
    desc: "获取投票详情",
    path: "/arts/voted",
    mockPath: "/arts/voted",
    params: {
      sn: "",
    },
    options: {},
  },
  {
    name: "getAuctions",
    method: "GET",
    desc: "获取市场-定时拍卖",
    path: "/auctions",
    mockPath: "/auctions",
    params: {
      sn: "",
      page: "",
      per_page: "",
    },
    options: {},
  },
  {
    name: "getAuctionById",
    method: "GET",
    desc: "通过id获取市场-定时拍卖",
    path: "/auctions/{:id}",
    mockPath: "/auctions/{:id}",
    params: {
      aid: "",
      sn: "",
    },
    options: {},
  },
  {
    name: "getAuctionBidsById",
    method: "GET",
    desc: "通过id获取市场定时拍卖的竞价历史记录",
    path: "/auctions/{:id}/bids",
    mockPath: "/auctions/{:id}/bids",
    params: {
      aid: "",
      sn: "",
    },
    options: {},
  },
  {
    name: "getAuctionsGroup",
    method: "GET",
    desc: "获取竞拍组(出价数)",
    path: "/auctions/group",
    mockPath: "/auctions/group",
    params: {},
    options: {},
  },
  {
    name: "getAuctionsGroupVotes",
    method: "GET",
    desc: "获取竞拍组(投票数)",
    path: "/auctions/details",
    mockPath: "/auctions/details",
    params: {},
    options: {},
  },
  {
    name: "getRecommend",
    method: "GET",
    desc: "获取首页推荐",
    path: "/arts/recommend",
    mockPath: "/arts/recommend",
    params: {
      sn: "",
    },
    options: {},
  },
  {
    name: "getAuctionsRecommend",
    method: "GET",
    desc: "获取首页拍卖推荐",
    path: "/auctions/recommend",
    mockPath: "/auctions/recommend",
    params: {
      sn: "",
      size: 4,
    },
    options: {},
  },
  {
    name: "getArtOrderRecommend",
    method: "GET",
    desc: "获取首页一口价推荐",
    path: "/art_orders/recommend",
    mockPath: "/art_orders/recommend",
    params: {
      sn: "",
      size: 4,
    },
    options: {},
  },
  {
    name: "getArtOrder",
    method: "GET",
    desc: "获取市场一口价",
    path: "/art_orders",
    mockPath: "/art_orders",
    params: {
      sn: "",
      page: "",
      per_page: "",
      erc_type: "",
    },
    options: {},
  },
  {
    name: "getArtOrderById",
    method: "GET",
    desc: "获取市场一口价",
    path: "/art_orders/{:id}",
    mockPath: "/art_orders/{:id}",
    params: {
      sn: "",
    },
    options: {},
  },
  {
    name: "getAuctionVersion",
    method: "GET",
    desc: "获取合约地址",
    path: "/arts/contracts",
    mockPath: "/arts/contracts",
    params: {},
    options: {},
  },
  {
    name: "getSouvenirsSortTypes",
    method: "GET",
    desc: "获取纪念品排序类型",
    path: "/souvenirs/sort_types",
    mockPath: "/souvenirs/sort_types",
    params: {},
    options: {},
  },
  {
    name: "getSouvenirsList",
    method: "GET",
    desc: "纪念品列表",
    path: "/souvenirs/list",
    mockPath: "/souvenirs/list",
    params: {},
    options: {},
  },
  {
    name: "getSouvenirById",
    method: "GET",
    desc: "纪念品详情",
    path: "/souvenirs/{:id}",
    mockPath: "/souvenirs/{:id}",
    params: {},
    options: {},
  },
  {
    name: "getSouvenirOrders",
    method: "GET",
    desc: "纪念品详情",
    path: "/souvenirs/{:id}/orders",
    mockPath: "/souvenirs/{:id}/orders",
    params: {},
    options: {},
  },
  {
    name: "getSettings",
    method: "GET",
    desc: "纪念品详情",
    path: "/arts/settings",
    mockPath: "/arts/settings",
    params: {},
    options: {},
  },
  {
    name: "getSouvenirChart",
    method: "GET",
    desc: "纪念品价格走势",
    path: "/souvenirs/{:id}/charts",
    mockPath: "/souvenirs/{:id}/charts",
    params: {
      period: "",
      token: "",
    },
    options: {},
  },
];

export default apiList;
