const apiList = [
  {
    name: "login",
    method: "POST",
    desc: "登录",
    path: "/members/user_address_login",
    mockPath: "/members/user_address_login",
    params: {
      address: "",
      message: "",
      signature: "",
    },
    options: {},
  },
  {
    name: "logout",
    method: "POST",
    desc: "退出登录",
    path: "/members/logout",
    mockPath: "/members/logout",
    params: {},
    options: {},
  },
  {
    name: "loginMessage",
    method: "GET",
    desc: "获取登录凭证",
    path: "/members/get_login_message",
    mockPath: "/members/get_login_message",
    params: {},
    options: {},
  },
  {
    name: "checkAddress",
    method: "GET",
    desc: "地址检查",
    path: "/members/check_address",
    mockPath: "/members/check_address",
    params: {
      address: "",
    },
    options: {},
  },
  {
    name: "getInfo",
    method: "GET",
    desc: "获取用户信息",
    path: "/members/info",
    mockPath: "/members/info",
    params: {},
    options: {},
  },
  {
    name: "postSignUp",
    method: "POST",
    desc: "注册",
    path: "/members/signup",
    mockPath: "/members/signup",
    params: {
      address: "",
      message: "",
      signature: "",
      email: "",
      nickname: "",
    },
    options: {},
  },
  {
    name: "getAssets",
    method: "GET",
    desc: "我的资产",
    path: "/arts/assets",
    mockPath: "/arts/assets",
    prefix: "",
    params: {},
    options: {},
  },
  {
    name: "getMineNFT",
    method: "GET",
    desc: "我的收藏",
    path: "/arts/mine",
    mockPath: "/arts/mine",
    params: {},
    options: {},
  },
  {
    name: "getOrderNFT",
    method: "GET",
    desc: "我的挂单",
    path: "/art_orders/mine",
    mockPath: "/art_orders/mine",
    params: {},
    options: {},
  },
  {
    name: "getUnbindHistory",
    method: "GET",
    desc: "我的解绑",
    path: "/arts/unbind",
    mockPath: "/arts/unbind",
    params: {},
    options: {},
  },
  {
    name: "getMyVotes",
    method: "GET",
    desc: "我的解绑",
    path: "/arts/my_voting",
    mockPath: "/arts/my_voting",
    params: {},
    options: {},
  },
  {
    name: "getMyRewards",
    method: "GET",
    desc: "我的奖励",
    path: "/arts/rewards",
    mockPath: "/arts/rewards",
    params: {},
    options: {},
  },
  {
    name: "getMigrate",
    method: "GET",
    desc: "获取迁移信息",
    path: "/arts/mr",
    mockPath: "/arts/mr",
    params: {},
    options: {},
  },
  {
    name: "collectedSouvenirs",
    method: "GET",
    desc: "可收集纪念品清单",
    path: "/souvenirs",
    mockPath: "/souvenirs",
    params: {},
    options: {},
  },
  {
    name: "collectMySouvenir",
    method: "POST",
    desc: "收集我的纪念品",
    path: "/souvenirs/collect",
    mockPath: "/souvenirs/collect",
    params: {
      uuid: "",
    },
    options: {},
  },
  {
    name: "getSouvenirsMine",
    method: "GET",
    desc: "我的纪念品列表",
    path: "/souvenirs/mine",
    mockPath: "/souvenirs/mine",
    params: {},
    options: {},
  },
  {
    name: "getSouvenirsStatus",
    method: "GET",
    desc: "纪念品状态",
    path: "/souvenirs/my_orders",
    mockPath: "/souvenirs/my_orders",
    params: {
      state: "",
    },
    options: {},
  },
  {
    name: "getPinnedList",
    method: "GET",
    desc: "已pin艺术品列表",
    path: "/arts/pinned",
    mockPath: "/arts/pinned",
    params: {},
    options: {},
  },
];

export default apiList;
