const apiList = [
  {
    name: "login",
    method: "POST",
    desc: "登录",
    path: "/members/user_address_login",
    mockPath: "/members/user_address_login",
    params: {
      address: "",
      message: "",
      signature: "",
    },
    options: {},
  },
  {
    name: "logout",
    method: "POST",
    desc: "退出登录",
    path: "/members/logout",
    mockPath: "/members/logout",
    params: {},
    options: {},
  },
  {
    name: "loginMessage",
    method: "GET",
    desc: "获取登录凭证",
    path: "/members/get_login_message",
    mockPath: "/members/get_login_message",
    params: {},
    options: {},
  },
  {
    name: "checkAddress",
    method: "GET",
    desc: "地址检查",
    path: "/members/check_address",
    mockPath: "/members/check_address",
    params: {
      address: "",
    },
    options: {},
  },
  {
    name: "getInfo",
    method: "GET",
    desc: "获取用户信息",
    path: "/members/info",
    mockPath: "/members/info",
    params: {},
    options: {},
  },
  {
    name: "postSignUp",
    method: "POST",
    desc: "注册",
    path: "/members/signup",
    mockPath: "/members/signup",
    params: {
      address: "",
      message: "",
      signature: "",
      email: "",
      nickname: "",
    },
    options: {},
  },
];

export default apiList;
